name: Docker CI

on:
  push:
    branches:
      - 'main'
      
  schedule:
    - cron: '45 * * * *'
env:
 # TODO: Change variable to your image's name.
 IMAGE_NAME: travisci_reverseproxy
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
